branch-defaults:
  main:
    environment: xenobackend-dev
global:
  application_name: xenobackend
  branch: null
  default_ec2_keyname: jhkey
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
